# Generated by Django 4.0.3 on 2022-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maincomn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_id', models.BigIntegerField()),
                ('u_name', models.CharField(max_length=20)),
                ('u_id', models.BigIntegerField()),
                ('content', models.CharField(max_length=100)),
                ('p_time', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au_id', models.BigIntegerField()),
                ('body', models.TextField()),
                ('content', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=15)),
                ('tag', models.CharField(max_length=10)),
                ('put_time', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.IntegerField()),
                ('coll_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcomn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.BigIntegerField()),
                ('u_name', models.CharField(max_length=20)),
                ('u_id', models.BigIntegerField()),
                ('content', models.CharField(max_length=100)),
                ('p_time', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
