# Generated by Django 4.0.3 on 2022-05-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_note_content_noteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteimage',
            name='image',
            field=models.ImageField(upload_to='img_url/'),
        ),
    ]
