# Generated by Django 4.0.3 on 2022-05-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_noteimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='identity',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
